### ISSUE TITLE
Pause on hover?

### ISSUE THREAD

**Issue by morrow95** [Script47/Toast#6]
Doing some research on the new BS4 toasts which led me here.  Looking to change from my current toasts plugin to BS4's.  This is basically what I was looking for (calling on the fly by passing options), but was hoping you added a pause on hover option... is that on the roadmap?

**Comment by Script47** [comment]
@morrow95 

This sounds like a good idea though unsure how feasible it is.

I'll give it a bash and will report back. Feel free to have a go yourself and make a pull request if anything avails.

**Comment by morrow95** [comment]
Will do.  I have some other things to do first before I get around to changing the toasts, but when I do, and if you haven't looked at it, I will play around with it a bit.

**Comment by Script47** [comment]
@morrow95 

Have a play around with this: https://jsfiddle.net/17vtnomc/ more specifically the 'Pause on Hover' button, let me know if you come across any issues so they can be fixed. If it seems to work let me know, I'll do some more testing and release a patch.

For those wondering how this has been accomplished, the toast has been set to never hide when the `pause_on_hover` key is passed (as `true`), to determine when to hide the toast we calculate when the toast should be hidden (`unix time + delay`) and save that as a data property (`hide-timestamp`), we then fire the following code to attach for toast to hidden when using `pause_on_hover`:

```
if (pause_on_hover !== false) {
    setTimeout(function() {
        if (!pause) {
            $('#' + id).toast('hide');
        }
    }, delay);

    $(document).on('mouseover', '#' + id, function() {
        pause = true;
    });

    $(document).on('mouseleave', '#' + id, function() {
        var current = Math.floor(Date.now() / 1000),
            future = parseInt($(this).data('hide-timestamp'));

        pause = false;

        if (current >= future) {
            $(this).toast('hide');
        }
    });
}
```

The timeout has been used to hide the toast if no-one has actually hovered over the toast once the delay has passed *and* if you aren't currently hovering on the toast, if you are hovering on the toast then this timeout won't fire again but `mouseleave` event will trigger the hide. The `mouseleave` event simply figures out if we need to hide the toast or not, the rest I'm sure you can piece together.

**Comment by morrow95** [comment]
The logic looks good.  I was actually going to try out everything tonight so this makes it even better.  Will let you know when I have some time to play with it later.

**Comment by Script47** [comment]
@morrow95 

I plan on pushing this sometime tonight, let me know if you have any suggestions.

**Comment by morrow95** [comment]
@Script47 Don't hold on me for anything as I still haven't had time to play around with the new toasts or anything you have done.  Whenever I get around to that I will chime in on what I come across.

**Comment by Script47** [comment]
I have pushed out an update for this feature request.

**Comment by morrow95** [comment]
@Script47 Sorry for not getting back sooner.  I ended up doing my own implementation from scratch last week.  Did things quite a bit different than yours especially as far as the hover goes.  I still have a few loose ends to do with the project, but if I get around to it I'll makeup a standalone version of what I did for the toasts including the css and everything.

The css caused the biggest trouble for me while trying to get the animation (both on/off) correct and working properly when multiple toasts were stacked.  My hover will pause on hover of any single toast, when mouse out occurs it resumes from where it left off, you can mouse in/out as many times as you want and repeat that behavior until there is no time left.  I did not use data values - it is just a js timer for each toast with this functionality.

**Comment by Script47** [comment]
@morrow95 

I'd be interested to see your implementation just ping here once you get around to making it public.
